language: java

jdk:
  - oraclejdk8

env:
  global:
  - secure: N30+tQHzr7i05iIbVf6YAk7i3ykPjZLxEZur3cZWh5vwD4TmQI9FDZ5vVJo3HWulb8tCV5jFM0RXwo2nswhq2G8WGJY6DkjICF1/U3FPax2VdgDEMScfULvRbt5f6NugHo5sbUuVPukVKv4+7LBdOuBOFXQ92OfEm9HQVO6PSzg5jgHeSJSEmh1cW+Zn6fSRVBP7+1A1HO/i0zdccA4noxx+pbhWp28GM7z2jnQ5x21Up9Zs4HA599r3pTYQuguzeaUzJh9GXMRh6xio1FgDfQ2wJe/0cTR+ZXcZNefX9LKo+eKNeez3ylgxkq48THtIfko5I7DBnm8omGbMSgoX1HF8CVgBD8igHUjN7nk+xbIR6aJLGaoZfdwxb/th2jayoj6JNp2v21KbmoTWlmUnOx5tFXAJIf1Y8+tl6PEfPmlz+LCXug6xhLTg67yD4Ee2EjMje9AUsbOjc033PMgszMPajjN5+m497ys7d7v+qU/6WeXh4OKGg04jkFw0hAghYd/+0twe9iUgPaFTm+pfmOKkOQjj9g8mhwwqQ57OdPzqDBl7EWNjHQtMgF0whWfitWzYUaqHUdRke4M74G9Albr8iK3IUXGBf/UKj8xWYF92J6TdgkNuMT1CR4XaYdYqyu4B6fjvCHXfaukt8G00y4cnY7OPTd4JEdwwTPSBvHQ=
  # A Google Cloud Storage secret (`GCS_SECRET`) for test execution data storage.
  - secure: tnnoDKT8QMEj7270VTYIj26c/rU3uBuNKl/j1SlKkZPM4xtFgkNnC4AEdtZ5JNJtDvGEdFe93Q8SQ/eKwZtORPWPFFRjmxqOsmJhC9yFtS/53JryMZGFyOnfv2iuKafRgHkwH6MAQByeA9rm3hyFle3R8w25CzwqaivbR3rdZol1aWVXCTpcxf5e3NvUijTKkm1coPIDAaw8F9Y+A5rth/X9QH6DkZJtIw89TXTanZDsmymqD8aiR4QVcsaEqrpOauSF9aLFZ/Y+DF+MgmDTNpNZlHdxzxuwb1qy3mFcKRp452vO0ufNmWxQPjXI1avTcwsRLaAxZHFLAoMZ+lSgD3chPAIFDPPak7wXB+2G0PMqKQk/9xreweqYxGCS6ousaMxzlC0U32gYcc825/+3kUr5ox/id7fjDoSI2Fd4tM4cdaKomKa6T4HNPM1Puzfqtd1aW2hUotAc0t3k+q0FaxwEISx0rRSz3VH1VoTMhf5K45EYaayoU20zMdRKNfQ7H6NkM622KSjMTx36D+cyuzgvZRqKNRTgXT5IpOJeMzmDpaGNeFwLaJGXTSpLM0Bio0T26W4ZhBNY8cTpBOpePxYdFnZEwouS8YO98UMsVq1KvAWYi6/xI/nbt+FXSmelvSvcmrC+7UatehlwuyDQTSiXqynO+37V7/CJ7zUqRjQ=
before_install:
  - chmod +x gradlew
  - chmod +x ./scripts/start-datastore.sh
  # Decrypt the credentials file and copy it over to the destination.
  - openssl aes-256-cbc -K $encrypted_ebb86cbccb5d_key -iv $encrypted_ebb86cbccb5d_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar
  # Create a target folder for the credentials file of Google Cloud, and copy it.
  - mkdir -p ./datastore/src/test/resources/
  - cp spine-dev.json ./datastore/src/test/resources/spine-dev-62685282c0b9.json

script:
  - ./gradlew build --stacktrace

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./config/scripts/publish-artifacts.sh
  - ./config/scripts/publish-artifacts.sh

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)

  # Publish Codacy reports
  - chmod +x ./config/scripts/report-coverage.sh
  - ./config/scripts/report-coverage.sh

after_script:
- chmod +x ./scripts/upload-artifacts.sh
- ./scripts/upload-artifacts.sh
