language: java

jdk:
  - openjdk8

env:
  global:
  # A Google Cloud Storage secret (`GCS_SECRET`) for test execution data storage.
  - secure: tnnoDKT8QMEj7270VTYIj26c/rU3uBuNKl/j1SlKkZPM4xtFgkNnC4AEdtZ5JNJtDvGEdFe93Q8SQ/eKwZtORPWPFFRjmxqOsmJhC9yFtS/53JryMZGFyOnfv2iuKafRgHkwH6MAQByeA9rm3hyFle3R8w25CzwqaivbR3rdZol1aWVXCTpcxf5e3NvUijTKkm1coPIDAaw8F9Y+A5rth/X9QH6DkZJtIw89TXTanZDsmymqD8aiR4QVcsaEqrpOauSF9aLFZ/Y+DF+MgmDTNpNZlHdxzxuwb1qy3mFcKRp452vO0ufNmWxQPjXI1avTcwsRLaAxZHFLAoMZ+lSgD3chPAIFDPPak7wXB+2G0PMqKQk/9xreweqYxGCS6ousaMxzlC0U32gYcc825/+3kUr5ox/id7fjDoSI2Fd4tM4cdaKomKa6T4HNPM1Puzfqtd1aW2hUotAc0t3k+q0FaxwEISx0rRSz3VH1VoTMhf5K45EYaayoU20zMdRKNfQ7H6NkM622KSjMTx36D+cyuzgvZRqKNRTgXT5IpOJeMzmDpaGNeFwLaJGXTSpLM0Bio0T26W4ZhBNY8cTpBOpePxYdFnZEwouS8YO98UMsVq1KvAWYi6/xI/nbt+FXSmelvSvcmrC+7UatehlwuyDQTSiXqynO+37V7/CJ7zUqRjQ=
  # Disable asking for user input for all Google Cloud SDK operations.
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
  - chmod +x gradlew
  - chmod +x ./scripts/install-gcloud.sh
  - chmod +x ./scripts/start-datastore.sh
  # Decrypt the credentials file and copy it over to the destination.
  - openssl aes-256-cbc -K $encrypted_ebb86cbccb5d_key -iv $encrypted_ebb86cbccb5d_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar
  # Install the complete gcloud SDK to access the Datastore emulator.
  - ./scripts/install-gcloud.sh
  # Add the newly installed gcloud SDK to PATH overriding the default Travis version.
  - source $HOME/google-cloud-sdk/path.bash.inc

script:
  - ./scripts/start-datastore.sh &
  - ./gradlew build --stacktrace

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./config/scripts/publish-artifacts.sh
  - ./config/scripts/publish-artifacts.sh

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)

after_script:
- chmod +x ./scripts/upload-artifacts.sh
- ./scripts/upload-artifacts.sh
