language: java

jdk:
  - oraclejdk7

before_install:
  - chmod +x gradlew
  - chmod +x ./scripts/start-datastore.sh
  - openssl aes-256-cbc -K $encrypted_16408b1fb58f_key -iv $encrypted_16408b1fb58f_iv -in ./datastore/src/test/resources/spine-dev-62685282c0b9.json.enc -out ./datastore/src/test/resources/spine-dev-62685282c0b9.json -d

script:
  - ./gradlew build codeCoverageReport --debug

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./scripts/publish-artifacts.sh
  - ./scripts/publish-artifacts.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
