language: java

#// TODO:09-11-16:dmytro.dashenkov: Configure javafx dependencies and change to oraclejdk7.
jdk:
  - oraclejdk8

before_script:
  - chmod +x ./gradlew

script:
  - ./gradlew check --debug
