language: java

jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew
  - chmod +x ./scripts/start-datastore.sh
  # Decrypt the Google Cloud credentials file and copy it over to the destination.
  - openssl aes-256-cbc -K $encrypted_af189f5020cd_key -iv $encrypted_af189f5020cd_iv -in spine-dev.json.enc -out spine-dev.json -d
  - pwd
  - ls -la
  - cp spine-dev.json ./datastore/src/test/resources/spine-dev-62685282c0b9.json

script:
  - ./gradlew build integrationTest codeCoverageReport --stacktrace

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./scripts/publish-artifacts.sh
  - ./scripts/publish-artifacts.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
