language: java

#// TODO:09-11-16:dmytro.dashenkov: Configure javafx dependencies and change to oraclejdk7.
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build --stacktrace

after_success:
  - chmod +x ./script/publish_artifacts.sh
  - ./script/publish_artifacts.sh
