language: java

jdk:
  - oraclejdk7

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build --debug
  - ./gradlew codeCoverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - chmod +x ./script/publish_artifacts.sh
  - ./script/publish_artifacts.sh
