language: java

jdk:
  - oraclejdk7

before_install:
  - chmod +x gradlew

script:
  - ./gradlew build --stacktrace

after_success:
  - chmod +x ./script/publish_artifacts.sh
  - ./script/publish_artifacts.sh
