# THe GAE Datastore sample indexes.

indexes:

  # Common index for all the applications.

  - kind: spine.base.Event
    ancestor: no
    properties:
    - name: type
    - name: created

  # Indexes for the Aggregates.
  #
  # Each custom Aggregate type must have such indexes in order to be retrieved properly.
  #
  # The Datastore kind represents the Protobuf type name of the Aggregate state. Both the property
  # names and the index directions should be kept unchanged.

  - kind: myapp.example.MyFirstAggregate
    properties:
    - name: aggregate_id
    - name: created
      direction: desc
    - name: version
      direction: desc
    - name: snapshot

  - kind: myapp.example.MySecondAggregate
    properties:
    - name: aggregate_id
    - name: created
      direction: desc
    - name: version
      direction: desc
    - name: snapshot
