# The indexes for Firestore in Datastore mode.

indexes:

  # Common index for all the applications.

  - kind: spine.core.Event
    ancestor: no
    properties:
      - name: type
      - name: created

  # Index required for `DsInboxStorage.readAll` query.

  - kind: spine.server.delivery.InboxMessage
    ancestor: yes
    properties:
      - name: inbox_shard
      - name: of_total_inbox_shards
      - name: received_at
      - name: version

  # Index required for `DsInboxStorage.newestMessageToDeliver` query.

  - kind: spine.server.delivery.InboxMessage
    ancestor: yes
    properties:
      - name: inbox_shard
      - name: of_total_inbox_shards
      - name: status

  # Indexes for the Aggregates.
  #
  # Each custom Aggregate type must have such indexes in order to be retrieved properly.
  #
  # The Datastore kind represents the Protobuf type name of the Aggregate state. Both the property
  # names and the index directions should be kept unchanged.

  - kind: myapp.example.MyFirstAggregate # Replace with your Aggregate Protobuf type name.
    # Copy as is:
    # ------------------
    properties:
      - name: aggregate_id
      - name: created
        direction: desc
      - name: version
        direction: desc
      - name: snapshot
    # ------------------

  - kind: myapp.example.MySecondAggregate # Replace with your Aggregate Protobuf type name.
    # Copy as is:
    # ------------------
    properties:
      - name: aggregate_id
      - name: created
        direction: desc
      - name: version
        direction: desc
      - name: snapshot
    # ------------------
